export interface Player {
    id?:number,
    fifa_version:string,
    fifa_update:string,
    player_face_url:string,
    long_name:string,
    player_positions:string,
    club_name:string,
    nationality_name:string,
    overall:number,
    potential:number,
    age:number,
    pace:number,
    shooting:number,
    passing:number,
    dribbling:number,
    defending:number,
    physic:number
}